package com.company.project.persistence.entities;

// Generated 19/04/2015 17:56:57 by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Users generated by hbm2java
 */
@Entity
@Table(name = "users", catalog = "Angular")
public class Users implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idUser", unique = true, nullable = false)
	private Integer idUser;

	@Column(name = "name", nullable = false)
	private String name;

	@Column(name = "lastname", nullable = true)
	private String lastname;

	@Column(name = "email", nullable = true)
	private String email;

	@Column(name = "role", nullable = true)
	private String role;

	@Column(name = "username", nullable = true)
	private String username;

	@Column(name = "password", nullable = true)
	private String password;

	@Column(name = "telephone", nullable = true)
	private String telephone;

	@Column(name = "mobile", nullable = true)
	private String mobile;

	public Users() {
	}

	public Users(String name, String lastname, String email, String username, String password, String telephone, String mobile, String role) {
		this.name = name;
		this.lastname = lastname;
		this.email = email;
		this.role = role;
		this.username = username;
		this.password = password;
		this.telephone = telephone;
		this.mobile = mobile;
	}

	public Integer getIdUser() {
		return this.idUser;
	}

	public void setIdUser(Integer idUser) {
		this.idUser = idUser;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getLastname() {
		return this.lastname;
	}

	public void setLastname(String lastname) {
		this.lastname = lastname;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getTelephone() {
		return this.telephone;
	}

	public void setTelephone(String telephone) {
		this.telephone = telephone;
	}

	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	public String getRole() {
		return role;
	}

	public void setRole(String role) {
		this.role = role;
	}

	@Override
	public int hashCode() {
		int hash = 0;
		hash += (idUser != null ? idUser.hashCode() : 0);
		return hash;
	}

	@Override
	public boolean equals(Object object) {
		if (object == null)
			return false;

		if (!(object instanceof Users)) {
			return false;
		}
		Users other = (Users) object;
		if ((this.idUser == null && other.idUser != null) || (this.idUser != null && !this.idUser.equals(other.idUser))) {
			return false;
		}
		return true;
	}

	@Override
	public String toString() {
		return "entities.Users[idUser=" + idUser + ", name=" + name + "]";
	}

}
